apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles:
    # GitHub Actions OIDC IAM Role for CI/CD
    - rolearn: arn:aws:iam::448049822550:role/github-oidc-role
      username: github
      groups:
        - system:masters
