# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: microservice-svc
  namespace: microservices
spec:
  selector:
    app: microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

